import inspect
import requests
from bs4 import BeautifulSoup

BASE_URL='https://matrix.brightmls.com/Matrix/Public/'
def launch(url = None):
	if url is None:
		print("you need to type a url to start")
		url =  "https://matrix.brightmls.com/Matrix/Public/PhotoPopup.aspx?tid=9&mtid=1&L=1&key=627224603&n=21&i=0&View=G"
	
	page = requests.get(url)
	soup = BeautifulSoup(page.text, 'html5lib')
	tables = soup.find_all('tr', {'class': 'imageRow'})
	for tr in tables:
		for x in parseGalleryTables(tr):
			print(x)
	
		
		
	
	
	
def parseGalleryTables(tr_imageRow):
	"""
	Name:		parseGalleryTables
	return:		list of html links
	
	Purpose: 	take a table row, and parse for IMG links
				return a list of all links found
	"""
	tmp = tr_imageRow.find_all('a')
	results = []
	for elm in tmp:
		results.append(BASE_URL + str(elm['href']) )
	
	return results

		
def getImageLink(url=None):
	"""
	Name:		getImageLink
	return:		tuple of IMG link, and photo title
	
	Purpose: 	take links generated by parseGalleryTables	
				and return the direct IMG link and it's title
				as a tuple (link, title)
	"""
	if url is None:
		url = "https://matrix.brightmls.com/Matrix/Public/PhotoPopup.aspx?tid=9&mtid=1&L=1&key=627224603&n=21&i=0&View=Y"
	page = requests.get(url)
	soup = BeautifulSoup(page.text, 'html5lib')
	imgs = soup.find_all('img', {'class' : 'IV_Image'})
	titles = soup.find_all('div', {'id': 'PopupCaption'})

	return imgs[0]['src'], titles[0].text
		
def savePhoto():
	import urllib
	f = open('00000001.jpg','wb')
	f.write(urllib.urlopen('http://www.gunnerkrigg.com//comics/00000001.jpg').read())
	f.close()
	
	import requests
	f = open('00000001.jpg','wb')
	f.write(requests.get('http://www.gunnerkrigg.com//comics/00000001.jpg').content)
	f.close()
	
	# this works
	# urllib.request.urlretrieve(getImageLink(), '1.jpg')